name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  lint-report:
    uses: canonical/identity-credentials-workflows/.github/workflows/lint-report.yaml@v0
    name: Lint report

  static-analysis:
    name: Static analysis
    uses: canonical/identity-credentials-workflows/.github/workflows/static-analysis.yaml@v0

  unit-tests-with-coverage:
    uses: canonical/identity-credentials-workflows/.github/workflows/unit-test.yaml@v0

  integration-test-v0:
    name: Integration tests for v0
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: sudo snap install --classic astral-uv
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.31-strict/stable
          juju-channel: 3.6/stable
          lxd-channel: 5.21/stable
      - name: Run tests using tox
        run: tox -e integration -- -k V0
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
  
  integration-test-v1:
    name: Integration tests for v1
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: sudo snap install --classic astral-uv
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.31-strict/stable
          juju-channel: 3.6/stable
          lxd-channel: 5.21/stable
      - name: Run tests using tox
        run: tox -e integration -- -k V1
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz

  publish-charm:
    name: Publish Charm
    needs: [integration-test-v0, integration-test-v1]
    runs-on: ubuntu-24.04
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.6.3
        id: channel
      - name: Upload charm to Charmhub
        uses: canonical/charming-actions/upload-charm@2.6.3
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

  publish-lib:
    runs-on: ubuntu-24.04
    name: Charmhub upload lib
    needs:
      - publish-charm
    if: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish libs
        uses: canonical/charming-actions/release-libraries@2.6.3
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
